apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres-catalog;Port=5432;Database=fcg_catalogo;Username=<DB_USER>;Password=<DB_PASSWORD>
  ConnectionStrings__Redis: redis:6379,abortConnect=false
  RabbitMQ__Username: <RABBITMQ_USER>
  RabbitMQ__Password: <RABBITMQ_PASSWORD>
  MongoDB__ConnectionString: <MONGODB_CONNECTION_STRING>
  MongoDB__DatabaseName: <MONGODB_DATABASE_NAME>
  Elasticsearch__CloudId: <ELASTICSEARCH_CLOUD_ID>
  Elasticsearch__ApiKey: <ELASTICSEARCH_API_KEY>
