apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: fcg
data:
  RabbitMQ__Host: rabbitmq
  RabbitMQ__VirtualHost: /
  Pagamento__TaxaReprovacao: "0.30"
  OTEL_SERVICE_NAME: PaymentsAPI
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317