apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z postgres-payment 5432; do
                echo "Aguardando banco de dados payment..."
                sleep 3
              done
              echo "Banco OK!"

        - name: wait-for-rabbitmq
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z rabbitmq 5672; do
                echo "Aguardando RabbitMQ..."
                sleep 3
              done
              echo "RabbitMQ OK!"

      containers:
      - name: payment-api
        image: ghcr.io/11nettg30/fcg-payments-api:latest
        ports:
          - containerPort: 8080
        envFrom:
          - secretRef:
              name: payment-secret
          - configMapRef:
              name: payment-config