apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres-payment;Port=5432;Database=fcg_payments;Username=fcgadmin;Password=fcgadminpass
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  OTEL_EXPORTER_OTLP_HEADERS: api-key=92d62e2884d0f3d8fa65b24c1bb2e411FFFFNRAL