apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres-payment;Port=5432;Database=fcg_payments;Username=<DB_USER>;Password=<DB_PASSWORD>
  RabbitMQ__Username: <RABBITMQ_USER>
  RabbitMQ__Password: <RABBITMQ_PASSWORD>
