apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: fcg
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=postgres-payment;Port=5432;Database=fcg_payments;Username=<DB_USER>;Password=<DB_PASSWORD>
  RABBITMQ_USER: <RABBITMQ_USER>
  RABBITMQ_PASSWORD: <RABBITMQ_PASSWORD>
  OTEL_EXPORTER_OTLP_HEADERS: api-key=<NEW_RELIC_API_KEY>
