apiVersion: v1
kind: Secret
metadata:
  name: postgres-payment-secret
  namespace: fcg
type: Opaque
stringData:
  POSTGRES_USER: <DB_USER>
  POSTGRES_PASSWORD: <DB_PASSWORD>
  POSTGRES_DB: fcg_payments
