apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-users
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-users
  template:
    metadata:
      labels:
        app: postgres-users
    spec:
      containers:
      - name: postgres
        image: postgres:18.1
        ports:
          - containerPort: 5432
        envFrom:
          - secretRef:
              name: postgres-users-secret
        volumeMounts:
          - mountPath: /var/lib/postgresql
            name: postgres-storage
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-users-pvc
