apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
  namespace: fcg
data:
  RabbitMQ__Host: rabbitmq
  RabbitMQ__VirtualHost: /
  Jwt__Authority: http://users-api
  Jwt__Audiencia: fcg-services
  Documentacao__Habilitada: "true"
  OTEL_SERVICE_NAME: CatalogAPI
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
